var Sessions = [
	{ id: "andreasneuhauser", image: "assets/speakers/andreas neuhauser.png"},
	{ id: "andrekraemer", image: "assets/speakers/andré krämer.jpg" },
	{ id: "andyclymer", image: "assets/speakers/andy clymer.jpg" },
	{ id: "annikafeick", image: "assets/speakers/annika feick.jpg" },
	{ id: "arturspeth", image: "assets/speakers/artur speth.jpg" },
	{ id: "boriswehrle", image: "assets/speakers/boris wehrle.jpg" },
	{ id: "carolalilienthal", image: "assets/speakers/carola lilienthal.jpg" },
	{ id: "christianbinder", image: "assets/speakers/christian binder.png"},	
	{ id: "christiangiesswein", image: "assets/speakers/christiangiesswein.jpg" },
	{ id: "christiangross", image: "assets/speakers/christian gross.png" },
	{ id: "christianliebel", image: "assets/speakers/christian liebel.jpg" },
	{ id: "christiannagel", image: "assets/speakers/christian nagel.jpg" },
	{ id: "christianwenz", image: "assets/speakers/christian wenz.jpg" },
	{ id: "christianweyer", image: "assets/speakers/christian weyer.png"},
	{ id: "christophseck", image: "assets/speakers/christoph seck.jpg" },
	{ id: "constantinklein", image: "assets/speakers/constantin klein.jpg" },
	{ id: "danielfisher", image: "assets/speakers/daniel fisher.jpg" },
	{ id: "daniellindemann", image: "assets/speakers/daniel lindemann.jpg" },
	{ id: "dariuszparys", image: "assets/speakers/dariusz parys.jpg" },
	{ id: "dinoesposito", image: "assets/speakers/dino esposito.jpg" },
	{ id: "dominickbaier", image: "assets/speakers/dominick baier.jpg" },
	{ id: "donwibier", image: "assets/speakers/don wibier.png" },
	{ id: "fabianmoritz", image: "assets/speakers/fabian moritz.jpg" },
	{ id: "frankduesterbeck", image: "assets/speakers/frank düsterbeck.png" },
	{ id: "gregorbiswanger", image: "assets/speakers/gregor biswanger.jpg" },
	{ id: "guentherfischer", image: "assets/speakers/günther fischer.jpg" },
	{ id: "hadihariri", image: "assets/speakers/hadi hariri.png" },
	{ id: "hendrikloesch", image: "assets/speakers/hendrik lösch.jpg" },
	{ id: "holgerschwichtenberg", image: "assets/speakers/holger schwichtenberg.jpg" },
	{ id: "inaeinemann", image: "assets/speakers/ina einemann.jpg" },
	{ id: "jayschmelzer", image: "assets/speakers/jay schmelzer.jpg" },
	{ id: "joachimfuchs", image: "assets/speakers/joachim fuchs.jpg" },
	{ id: "joergneumann", image: "assets/speakers/jörg neumann.jpg" },
	{ id: "juergengutsch", image: "assets/speakers/jürgen gutsch.jpg" },
	{ id: "karstenglied", image: "assets/speakers/karsten glied.jpg" },
	{ id: "karstenkempe", image: "assets/speakers/karsten kempe.jpg" },
	{ id: "kaygrebenstein", image: "assets/speakers/kay grebenstein.jpg" },
	{ id: "manfredsteyer", image: "assets/speakers/manfred steyer.jpg" },
	{ id: "manuelmayer", image: "assets/speakers/manuel meyer.jpg" },
	{ id: "manuelrauber", image: "assets/speakers/manuel rauber.jpg" },
	{ id: "marcmueller", image: "assets/speakers/marc müller.jpg" },
	{ id: "markusehrenmueller", image: "assets/speakers/markus ehrenmüller-jensen.jpg" },
	{ id: "martinuhlig", image: "assets/speakers/martin uhlig.jpg" },
	{ id: "matthiasfischer", image: "assets/speakers/matthias fischer.jpg" },
	{ id: "maxkleiner", image: "assets/speakers/max kleiner.jpg" },
	{ id: "mirkoschrempp", image: "assets/speakers/mirko schrempp.jpg" },
	{ id: "nenoloje", image: "assets/speakers/neno loje.jpg" },
	{ id: "nicoorschel", image: "assets/speakers/nico orschel.jpg" },
	{ id: "oliverscheer", image: "assets/speakers/oliver scheer.jpg" },
	{ id: "oliversturm", image: "assets/speakers/oliver sturm.jpg" },
	{ id: "oliviaklose", image: "assets/speakers/olivia klose.jpg" },
	{ id: "paulstack", image: "assets/speakers/paul stack.jpg" },
	{ id: "philipppendelin", image: "assets/speakers/philipp pendelin.jpg" },
	{ id: "pradeepmalage", image: "assets/speakers/pradeep malage.png" },
	{ id: "rainerstropek", image: "assets/speakers/rainer stropek.jpg" },
	{ id: "renehezser", image: "assets/speakers/rené hézser.jpg" },
	{ id: "ricardoniepel", image: "assets/speakers/ricardo niepel.jpg" },
	{ id: "richardblewett", image: "assets/speakers/richard blewett.jpg" },
	{ id: "robertpanther", image: "assets/speakers/robert panther.jpg" },
	{ id: "romanschacherl", image: "assets/speakers/roman schacherl.jpg" },
	{ id: "ruedigerschnirring", image: "assets/speakers/rüdiger schnirring.jpg" },
	{ id: "sabineberneckerbendixen", image: "assets/speakers/sabine bernecker-bendixen.jpg" },
	{ id: "santoshpatil", image: "assets/speakers/santosh patil.png" },
	{ id: "stefanhaupt", image: "assets/speakers/stefan haupt.jpg" },
	{ id: "stevebehrendt", image: "assets/speakers/steve behrendt.jpg" },
	{ id: "thomashilzendegen", image: "assets/speakers/thomas hilzendegen.png" },
	{ id: "thomasschissler", image: "assets/speakers/thomas schissler.jpg" },
	{ id: "thorstenhans", image: "assets/speakers/thorsten hans.jpg" },
	{ id: "thorstenkansy", image: "assets/speakers/thorsten kansy.jpg" },
	{ id: "ulrikestirnweiss", image: "assets/speakers/ulrike stirnweiß.jpg" },
	{ id: "ursenzler", image: "assets/speakers/urs enzler.jpg" },
	{ id: "uwericken", image: "assets/speakers/uwe ricken.jpg" },
	{ id: "wojtekprzibylla", image: "assets/speakers/wojtek przibylla.jpg" },
	{ id: "writeline", image: "assets/dparys.png" }
];